print("allSpades :")
print(Deck.allSpades)
print("allDiamonds :")
print(Deck.allDiamonds)
print("allHearts :")
print(Deck.allHearts)
print("allClubs :")
print(Deck.allClubs)
print("allCards :")
print(Deck.allCards)
